### ISSUE TITLE
window.__cmp not ready after bootstrap initialization

### ISSUE THREAD

**Issue by alextremp** [scm-spain/CMP#55]
**SUMMARY**
When the boros-cmp is imported and the init method is called it's expected to be able to use the window.__cmp function, but there's a race condition as the initialization runs in a Promise.

**STEPS TO REPRODUCE**
* Import the project
* Call the init method
* Call any window.__cmp command

**EXPECTED RESULT**
* The command is consumed with the window.__cmp function

**ACTUAL RESULT**
* There's a random error (race condition) indicating that window.__cmp is not a function

**Comment by victuxbb** [comment]
Definitely we should create documentation about the two possible ways of knowing when BorosCmp is ready:
* Using .then as response of init method (we must fix the error of missing return in bootstrap)
* Adding a window.document Listener for "cmpReady" event for legacy code

**Comment by rafamarquezv** [comment]
To initialize Boros CMP using [default configuration](#configuration-properties-and-default-values) values:

```javascript
import boroscmp from '@schibstedspain/boros-cmp'

boroscmp.init()
    .then(()=>{
        // do your stuff ...
    })
```

To initialize Boros CMP using customized configuration values:

```javascript
import boroscmp from '@schibstedspain/boros-cmp'

const customConfig = {
  gdpr: {
    gdprApplies: true,
    storeConsentGlobally: false
  },
  consent: {
    consentScreen: 1,
    consentLanguage: 'es'
  }
}

boroscmp.init({config: customConfig})
    .then(()=>{
        // do your stuff ...
    })
```

Notice that **init** method is returning a _Promise_ but you can subscribe to *cmpReady* event instead:
```javascript
import boroscmp from '@schibstedspain/boros-cmp'

boroscmp.init()

window.document.addEventListener("cmpReady", (event) =>{
  // do your stuff ...
  // like calling window.__cmp( ...
})

```

**Comment by rafamarquezv** [comment]
Solved in version -> @schibstedspain/boros-cmp@1.0.3

https://www.npmjs.com/package/@schibstedspain/boros-cmp
